version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - ./.env

    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
  resume:
    build: ./my_cv
    container_name: resume

volumes:
  mysql-data:

networks:
  default:
    external:
      name: docker_host
