version: '3'
services:
  backend:
    build: ./backend
    command: ./docker-entrypoint.sh
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app/backend

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A postfolio worker --loglevel=info
    depends_on:
      - backend

  resume:
    build: ./my_cv
    container_name: resume

volumes:
  db-data:
  redisdata:
networks:
  default:
    external: true
    name: npmAdmin
