version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ./docker-entrypoint.sh
    container_name: backend
    env_file:
      - ./.env

    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  resume:
    build: ./my_cv
    container_name: resume

volumes:
  postgres_data:
  static:

networks:
  default:
    external:
      name: docker_host
