version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    command: ./docker-entrypoint.sh
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app/backend

  resume:
    build: ./my_cv
    container_name: resume

volumes:
  db-data:
networks:
  default:
    external:
      name: docker_host
