# Generated by Django 4.1.3 on 2022-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_url', models.URLField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('project_image', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
