# Generated by Django 4.1.3 on 2022-11-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='projects.categories'),
            preserve_default=False,
        ),
    ]
